spring:
  datasource:
    url: ${MYSQL_DB_HOST:jdbc:mysql}:${MYSQL_DB_PORT://localhost:3306}/${MYSQL_SCHEMA_NAME:blog_engine}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_USER_PASSWORD:testtest}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      username: default
      host: ${DATA_REDIS_HOST:localhost}
      port: ${DATA_REDIS_PORT:6379}
      password: ${DATA_REDIS_PASSWORD:password}
  session:
    store-type: redis

app:
  upload:
    max-size: 5242880
    folder-path: ./upload/ab/cd/ef/
    relative-prefix: /upload/ab/cd/ef/

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: alexei.muraschkin@mail.ru
  copyright: Мурашкин Алексей
  copyrightfrom: 2021

time.expire.captcha: 1