spring.datasource.url: ${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/${MYSQL_SCHEMA_NAME}
spring.datasource.username: ${MYSQL_USERNAME}
spring.datasource.password: ${MYSQL_USER_PASSWORD}
spring.jpa.hibernate.ddl-auto: validate
spring.mvc.pathmatch.matching-strategy: ant_path_matcher
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: ${GMAIL_USERNAME}
spring.mail.password: ${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring:
  jpa:
    open-in-view: false

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: alexei.muraschkin@mail.ru
blog.copyright: Мурашкин Алексей
blog.copyrightfrom: 2021
time.expire.captcha: 1